# Generated by Django 4.0.3 on 2022-04-11 09:47

from django.db import migrations, models
import streamer.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='video/%y', validators=[streamer.validators.file_size])),
            ],
        ),
    ]
