# Generated by Django 4.0.3 on 2022-04-12 09:25

from django.db import migrations, models
import streamer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='image',
            field=models.FileField(default='', upload_to='image/%y', validators=[streamer.validators.file_size]),
        ),
    ]
