# Generated by Django 4.0.3 on 2022-04-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0002_videos_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
