# Generated by Django 4.0.3 on 2022-04-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0003_rename_image_videos_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.FileField(upload_to='image/%y'),
        ),
    ]
